worlds:
    world:
    - DXLQV0SZR
    - VPFJ6EG8I
    - O9GP9JW82
    - V1M04KSRI
    - LCV99UYOV
    - 91X9TGTOW
    - 1SB9NYBLJ
    - V8NRLPQJX
    - 1P2NAMLIV
    - PNODOXWKR
    - AZLP9OQ3O
    - 0DKJTHSEP
    - HFCTAI1G1
    - CANDLBSO4
    - TEIDKNQNE
    - C02A9CUMA
    - 2HGU9BJ22
    - V6Z2E92EN
    - 32SOGJT1P
    - IB26MV4JU
    - 0JMIK9WZY
    - EASYV0XN0
    - HOSMES6NY
    - LM5URY8UG
    - XVXBEMLIV
    - NM044BHL5
    - HYOQLXGTJ
    - 2ZHJ3MZS7
    - 5Q1I7R7X5
    - 6WBG16RYW
    - I0SY1BMAE
    - 82LISWMRZ
    - 3F0B6ZI6Z
    - BUOBAX56U
    - VAHV2H2Q8
    - QCGDML03E
    - JKXUH1UWX
    - N0RCASCME
    - 2GJDOE9JL
    - PYRFDTDS4
    - 8UOFJXM79
    - QZZVRY5M3
    - RFP004Y7J
    - JXBM85CHU
    - VRRFG2IJR
    - QUDE109HF
    - OANJRBMAE
    - IOURFV8HN
    - E4GG1I3XY
    - TKESEB580
    - 30XRKKVYV
    - ODA0QF89F
    - 4OGW53YQ9
    - Y5VJCD93C
    - NVRIHWZBU
    - SJMFAFNTX
    - FX6B65CHU
    - LP5EWK987
    - BPFIRMDM9
    - PICFKWIT6
    - AXXIAPS0U
    - FPJVZ6LJ6
    - ZLQ0339T8
    - 8P8M9HVL2
    - U16QKVMBP
    - SJKV69WZY
