import crafttweaker.liquid.ILiquidStack;

//Steam Age
/*

*/

//Electrical Age
val fluidsEA = [
    //Immersive Engineering
    <liquid:napalm>,
    <liquid:exhauststeam>,
    <liquid:distwater>,
    <liquid:fluegas>,
    <liquid:plantoil>,
    <liquid:ethanol>,
    <liquid:biodiesel>,
    <liquid:concrete>,
    <liquid:potion>,
    <liquid:diesel>,
    <liquid:lubricant>,
    <liquid:gasoline>,
    <liquid:oil>,
    //Industrial Foregoing
    <liquid:if.ore_fluid_fermented>,
    <liquid:essence>,
    <liquid:meat>,
    <liquid:latex>,
    <liquid:sewage>,
    <liquid:sludge>,
    <liquid:biofuel>,
    <liquid:if.pink_slime>,
    <liquid:if.protein>,
    <liquid:if.ore_fluid_raw>,
    <liquid:if.ore_fluid_fermented>
    //
] as ILiquidStack[];

for f in fluidsEA{
    mods.ItemStages.stageLiquid("electrical", f);
}

//Atomic Age
val fluidsAA = [
    //Mekanism
    <liquid:brine>,
    <liquid:liquidlithium>,
    <liquid:heavywater>,
    <liquid:hydrogen>,
    <liquid:oxygen>,
    //NuclearCraft
    <liquid:plutonium_238>,
    <liquid:plutonium_238_fluoride>,
    <liquid:plutonium_238_fluoride_flibe>,
    <liquid:plutonium_239>,
    <liquid:plutonium_239_fluoride>,
    <liquid:plutonium_239_fluoride_flibe>,
    <liquid:plutonium_241>,
    <liquid:plutonium_241_fluoride>,
    <liquid:plutonium_241_fluoride_flibe>,
    <liquid:thorium>,
    <liquid:thorium_fluoride>,
    <liquid:thorium_fluoride_flibe>,
    <liquid:uranium>,
    <liquid:uranium_fluoride>,
    <liquid:uranium_fluoride_flibe>,
    <liquid:plutonium>,
    <liquid:plutonium_fluoride>,
    <liquid:plutonium_fluoride_flibe>,
    <liquid:thorium_230>,
    <liquid:thorium_230_fluoride>,
    <liquid:thorium_230_fluoride_flibe>,
    <liquid:uranium_233>,
    <liquid:uranium_233_fluoride>,
    <liquid:uranium_233_fluoride_flibe>,
    <liquid:uranium_235>,
    <liquid:uranium_235_fluoride>,
    <liquid:uranium_235_fluoride_flibe>,
    <liquid:uranium_238>,
    <liquid:uranium_238_fluoride>,
    <liquid:uranium_238_fluoride_flibe>,
    <liquid:neptunium_236>,
    <liquid:neptunium_236_fluoride>,
    <liquid:neptunium_236_fluoride_flibe>,
    <liquid:neptunium_237>,
    <liquid:neptunium_237_fluoride>,
    <liquid:neptunium_237_fluoride_flibe>,
    <liquid:fuel_lep_239>,
    <liquid:fuel_lep_239_fluoride>,
    <liquid:fuel_lep_239_fluoride_flibe>,
    <liquid:fuel_hep_239>,
    <liquid:fuel_hep_239_fluoride>,
    <liquid:fuel_hep_239_fluoride_flibe>,
    <liquid:fuel_lep_241>,
    <liquid:fuel_lep_241_fluoride>,
    <liquid:fuel_lep_241_fluoride_flibe>,
    <liquid:plutonium_242>,
    <liquid:plutonium_242_fluoride>,
    <liquid:plutonium_242_fluoride_flibe>,
    <liquid:americium_241>,
    <liquid:americium_241_fluoride>,
    <liquid:americium_241_fluoride_flibe>,
    <liquid:americium_242>,
    <liquid:americium_242_fluoride>,
    <liquid:americium_242_fluoride_flibe>,
    <liquid:curium_247>,
    <liquid:curium_247_fluoride>,
    <liquid:curium_247_fluoride_flibe>,
    <liquid:berkelium_247>,
    <liquid:berkelium_247_fluoride>,
    <liquid:berkelium_247_fluoride_flibe>,
    <liquid:berkelium_248>,
    <liquid:berkelium_248_fluoride>,
    <liquid:berkelium_248_fluoride_flibe>,
    <liquid:fuel_tbu>,
    <liquid:fuel_tbu_fluoride>,
    <liquid:fuel_tbu_fluoride_flibe>,
    <liquid:fuel_leu_233>,
    <liquid:fuel_leu_233_fluoride>,
    <liquid:fuel_leu_233_fluoride_flibe>,
    <liquid:fuel_heu_233>,
    <liquid:fuel_heu_233_fluoride>,
    <liquid:fuel_heu_233_fluoride_flibe>,
    <liquid:depleted_fuel_hep_241>,
    <liquid:depleted_fuel_hep_241_fluoride>,
    <liquid:depleted_fuel_hep_241_fluoride_flibe>,
    <liquid:depleted_fuel_lea_242>,
    <liquid:depleted_fuel_lea_242_fluoride>,
    <liquid:depleted_fuel_lea_242_fluoride_flibe>,
    <liquid:depleted_fuel_hea_242>,
    <liquid:depleted_fuel_hea_242_fluoride>,
    <liquid:depleted_fuel_hea_242_fluoride_flibe>,
    <liquid:fuel_hecm_243>,
    <liquid:fuel_hecm_243_fluoride>,
    <liquid:fuel_hecm_243_fluoride_flibe>,
    <liquid:fuel_lecm_245>,
    <liquid:fuel_lecm_245_fluoride>,
    <liquid:fuel_lecm_245_fluoride_flibe>,
    <liquid:fuel_hecm_245>,
    <liquid:fuel_hecm_245_fluoride>,
    <liquid:fuel_hecm_245_fluoride_flibe>,
    <liquid:fuel_lecf_249>,
    <liquid:fuel_lecf_249_fluoride>,
    <liquid:fuel_lecf_249_fluoride_flibe>,
    <liquid:fuel_hecf_249>,
    <liquid:fuel_hecf_249_fluoride>,
    <liquid:fuel_hecf_249_fluoride_flibe>,
    <liquid:fuel_lecf_251>,
    <liquid:fuel_lecf_251_fluoride>,
    <liquid:fuel_lecf_251_fluoride_flibe>,
    <liquid:depleted_fuel_leu_235>,
    <liquid:depleted_fuel_leu_235_fluoride>,
    <liquid:depleted_fuel_leu_235_fluoride_flibe>,
    <liquid:depleted_fuel_heu_235>,
    <liquid:depleted_fuel_heu_235_fluoride>,
    <liquid:depleted_fuel_heu_235_fluoride_flibe>,
    <liquid:depleted_fuel_len_236>,
    <liquid:depleted_fuel_len_236_fluoride>,
    <liquid:depleted_fuel_len_236_fluoride_flibe>,
    <liquid:americium_243>,
    <liquid:americium_243_fluoride>,
    <liquid:americium_243_fluoride_flibe>,
    <liquid:curium_243>,
    <liquid:curium_243_fluoride>,
    <liquid:curium_243_fluoride_flibe>,
    <liquid:curium_245>,
    <liquid:curium_245_fluoride>,
    <liquid:curium_245_fluoride_flibe>,
    <liquid:depleted_fuel_lecm_247>,
    <liquid:depleted_fuel_lecm_247_fluoride>,
    <liquid:depleted_fuel_lecm_247_fluoride_flibe>,
    <liquid:depleted_fuel_hecm_247>,
    <liquid:depleted_fuel_hecm_247_fluoride>,
    <liquid:depleted_fuel_hecm_247_fluoride_flibe>,
    <liquid:depleted_fuel_leb_248>,
    <liquid:depleted_fuel_leb_248_fluoride>,
    <liquid:depleted_fuel_leb_248_fluoride_flibe>,
    <liquid:depleted_fuel_hecf_251>,
    <liquid:depleted_fuel_hecf_251_fluoride>,
    <liquid:depleted_fuel_hecf_251_fluoride_flibe>,
    <liquid:redstone>,
    <liquid:redstone_nak>,
    <liquid:redstone_nak_hot>,
    <liquid:quartz>,
    <liquid:quartz_nak>,
    <liquid:quartz_nak_hot>,
    <liquid:liquidhelium_nak_hot>,
    <liquid:ender>,
    <liquid:ender_nak>,
    <liquid:ender_nak_hot>,
    <liquid:cryotheum>,
    <liquid:cryotheum_nak>,
    <liquid:cryotheum_nak_hot>,
    <liquid:iron_nak>,
    <liquid:iron_nak_hot>,
    <liquid:fuel_lecm_247>,
    <liquid:fuel_lecm_247_fluoride>,
    <liquid:fuel_lecm_247_fluoride_flibe>,
    <liquid:fuel_hecm_247>,
    <liquid:fuel_hecm_247_fluoride>,
    <liquid:fuel_hecm_247_fluoride_flibe>,
    <liquid:fuel_leb_248>,
    <liquid:fuel_leb_248_fluoride>,
    <liquid:fuel_leb_248_fluoride_flibe>,
    <liquid:californium_249>,
    <liquid:californium_249_fluoride>,
    <liquid:californium_249_fluoride_flibe>,
    <liquid:californium_250>,
    <liquid:californium_250_fluoride>,
    <liquid:californium_250_fluoride_flibe>,
    <liquid:californium_251>,
    <liquid:californium_251_fluoride>,
    <liquid:californium_251_fluoride_flibe>,
    <liquid:fuel_leu_235>,
    <liquid:fuel_leu_235_fluoride>,
    <liquid:fuel_leu_235_fluoride_flibe>,
    <liquid:fuel_heu_235>,
    <liquid:fuel_heu_235_fluoride>,
    <liquid:fuel_heu_235_fluoride_flibe>,
    <liquid:fuel_len_236>,
    <liquid:fuel_len_236_fluoride>,
    <liquid:fuel_len_236_fluoride_flibe>,
    <liquid:fuel_hep_241>,
    <liquid:fuel_hep_241_fluoride>,
    <liquid:fuel_hep_241_fluoride_flibe>,
    <liquid:fuel_lea_242>,
    <liquid:fuel_lea_242_fluoride>,
    <liquid:fuel_lea_242_fluoride_flibe>,
    <liquid:fuel_hea_242>,
    <liquid:fuel_hea_242_fluoride>,
    <liquid:fuel_hea_242_fluoride_flibe>,
    <liquid:depleted_fuel_heb_248>,
    <liquid:depleted_fuel_heb_248_fluoride>,
    <liquid:depleted_fuel_heb_248_fluoride_flibe>,
    <liquid:depleted_fuel_lecf_249>,
    <liquid:depleted_fuel_lecf_249_fluoride>,
    <liquid:depleted_fuel_lecf_249_fluoride_flibe>,
    <liquid:depleted_fuel_hecf_249>,
    <liquid:depleted_fuel_hecf_249_fluoride>,
    <liquid:depleted_fuel_hecf_249_fluoride_flibe>,
    <liquid:fuel_hecf_251>,
    <liquid:fuel_hecf_251_fluoride>,
    <liquid:fuel_hecf_251_fluoride_flibe>,
    <liquid:depleted_fuel_tbu>,
    <liquid:depleted_fuel_tbu_fluoride>,
    <liquid:depleted_fuel_tbu_fluoride_flibe>,
    <liquid:depleted_fuel_leu_233>,
    <liquid:depleted_fuel_leu_233_fluoride>,
    <liquid:depleted_fuel_leu_233_fluoride_flibe>,
    <liquid:depleted_fuel_hen_236>,
    <liquid:depleted_fuel_hen_236_fluoride>,
    <liquid:depleted_fuel_hen_236_fluoride_flibe>,
    <liquid:depleted_fuel_lep_239>,
    <liquid:depleted_fuel_lep_239_fluoride>,
    <liquid:depleted_fuel_lep_239_fluoride_flibe>,
    <liquid:depleted_fuel_hep_239>,
    <liquid:depleted_fuel_hep_239_fluoride>,
    <liquid:depleted_fuel_hep_239_fluoride_flibe>,
    <liquid:depleted_fuel_lecm_243>,
    <liquid:depleted_fuel_lecm_243_fluoride>,
    <liquid:depleted_fuel_lecm_243_fluoride_flibe>,
    <liquid:depleted_fuel_hecm_243>,
    <liquid:depleted_fuel_hecm_243_fluoride>,
    <liquid:depleted_fuel_hecm_243_fluoride_flibe>,
    <liquid:depleted_fuel_lecm_245>,
    <liquid:depleted_fuel_lecm_245_fluoride>,
    <liquid:depleted_fuel_lecm_245_fluoride_flibe>,
    <liquid:fuel_lecm_243>,
    <liquid:fuel_lecm_243_fluoride>,
    <liquid:fuel_lecm_243_fluoride_flibe>,
    <liquid:fuel_heb_248>,
    <liquid:fuel_heb_248_fluoride>,
    <liquid:fuel_heb_248_fluoride_flibe>,
    <liquid:depleted_fuel_heu_233>,
    <liquid:depleted_fuel_heu_233_fluoride>,
    <liquid:depleted_fuel_heu_233_fluoride_flibe>,
    <liquid:gold_nak>,
    <liquid:gold_nak_hot>,
    <liquid:glowstone>,
    <liquid:glowstone_nak>,
    <liquid:glowstone_nak_hot>,
    <liquid:lapis>,
    <liquid:lapis_nak>,
    <liquid:lapis_nak_hot>,
    <liquid:diamond>,
    <liquid:emerald>,
    <liquid:emerald_nak>,
    <liquid:emerald_nak_hot>,
    <liquid:copper>,
    <liquid:copper_nak>,
    <liquid:copper_nak_hot>,
    <liquid:tin>,
    <liquid:tin_nak>,
    <liquid:tin_nak_hot>,
    <liquid:curium_246>,
    <liquid:curium_246_fluoride>,
    <liquid:curium_246_fluoride_flibe>,
    <liquid:californium_252>,
    <liquid:californium_252_fluoride>,
    <liquid:californium_252_fluoride_flibe>,
    <liquid:fuel_hen_236>,
    <liquid:fuel_hen_236_fluoride>,
    <liquid:fuel_hen_236_fluoride_flibe>,
    <liquid:depleted_fuel_lep_241>,
    <liquid:depleted_fuel_lep_241_fluoride>,
    <liquid:depleted_fuel_lep_241_fluoride_flibe>,
    <liquid:depleted_fuel_hecm_245>,
    <liquid:depleted_fuel_hecm_245_fluoride>,
    <liquid:depleted_fuel_hecm_245_fluoride_flibe>,
    <liquid:depleted_fuel_lecf_251>,
    <liquid:depleted_fuel_lecf_251_fluoride>,
    <liquid:depleted_fuel_lecf_251_fluoride_flibe>,
    <liquid:diamond_nak>,
    <liquid:diamond_nak_hot>,
    <liquid:liquidhelium_nak>,
    <liquid:magnesium>,
    <liquid:magnesium_nak>,
    <liquid:magnesium_nak_hot>
] as ILiquidStack[];

for f in fluidsAA{
    mods.ItemStages.stageLiquid("atomic", f);
}



















